/*
 * libobj.h - C ABI for the obj embedded document database.
 *
 * AUTO-GENERATED by cbindgen from crates/libobj/src/<modules>.rs.
 * Do NOT edit by hand: re-run cargo build -p libobj to
 * regenerate this file. A header_drift test in
 * crates/libobj/tests/header_drift.rs fails CI if the
 * committed copy disagrees with the freshly-generated output.
 *
 * Power-of-ten Rule 8: this header is the surface of the obj
 * unsafe boundary. Every function below has a documented
 * safety contract on the Rust side; consumers MUST observe the
 * pointer-ownership conventions noted in the docstrings.
 */

#ifndef LIBOBJ_H
#define LIBOBJ_H

#pragma once

/* AUTO-GENERATED — do not edit; regenerate via `cargo build -p libobj`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
/**
 * Maximum number of bytes that `obj_index_key_encode` can write for a
 * value of `value_len` raw bytes. Use this to size a stack buffer for
 * the encode call without the two-call size-query idiom: an encoded
 * field is at most `value_len + 5` bytes for any kind and any length.
 */
#define OBJ_INDEX_KEY_CAP(value_len) ((size_t)(value_len) + 5)


/**
 * Length in bytes of the [`obj_config_t::encryption_key`] field.
 * The master encryption key is always exactly 32 bytes
 * (XChaCha20-Poly1305 / HKDF master key width); the C contract
 * encodes the length in the type rather than a separate argument.
 */
#define OBJ_ENCRYPTION_KEY_LEN 32

/**
 * Opaque database handle.
 *
 * Created by [`obj_open`] / [`obj_open_with_config`]; freed by
 * [`obj_close`]. The Rust side holds an [`Arc<DbInner>`] (the
 * engine handle plus a `last_error` diagnostic slot) so future
 * transaction handles can each hold an `Arc` to outlive the
 * original [`obj_open`] return point AND reach the shared
 * `last_error` slot for [`obj_errmsg`].
 *
 * The struct is **opaque to C**: cbindgen emits a forward
 * declaration only (`typedef struct obj_db_t obj_db_t;`). The
 * Rust-side layout is NOT `#[repr(C)]` because the Arc field is
 * not C-compatible — C callers only ever see pointer-shaped
 * access via the API below.
 */
typedef struct obj_db_t obj_db_t;

/**
 * Opaque integrity report handle. Buffers the failure list so
 * per-failure access by index is cheap.
 */
typedef struct obj_integrity_report_t obj_integrity_report_t;

/**
 * Opaque iterator handle returned by `obj_iter_all` /
 * `obj_iter_index_range`. Drives one element at a time via
 * `obj_iter_next` and is freed by `obj_iter_free`.
 */
typedef struct obj_iter_t obj_iter_t;

/**
 * Opaque read-transaction handle. Same lifetime erasure pattern
 * as [`obj_write_txn_t`].
 */
typedef struct obj_read_txn_t obj_read_txn_t;

/**
 * Opaque write-transaction handle.
 *
 * Holds:
 *
 * - `inner`: a `'static`-erased [`WriteTxn`] borrowing from the
 *   shared env. Real lifetime is bound to the `_db` keepalive
 *   below; the erasure is sound because the two fields drop in
 *   the order declared (Rust guarantees in-declaration-order
 *   field drop) and the txn never escapes as `'static`.
 * - `_db`: an Arc keepalive on the parent [`obj::Db`]; the env
 *   referenced by `inner` lives at least as long as this Arc.
 *
 * `ManuallyDrop` on `inner` lets us explicitly drop the txn (via
 * `obj_txn_commit` / `obj_txn_rollback` / the handle's `Drop`)
 * before the Arc is released — order matters for soundness.
 */
typedef struct obj_write_txn_t obj_write_txn_t;

/**
 * Numeric type carried by `obj_error_t`. Aliased so the cbindgen
 * header emits `typedef int32_t obj_error_t;` rather than a bare
 * `int32_t` everywhere.
 */
typedef int32_t obj_error_t;

/**
 * A range bound passed by value across the C ABI.
 *
 * `ptr == NULL` (paired with `len == 0`) means unbounded on that side.
 * A non-null `ptr` points to `len` order-preserving encoded key bytes;
 * `inclusive` selects [`Bound::Included`] vs [`Bound::Excluded`].
 * `inclusive` is ignored when `ptr` is `NULL`.
 *
 * cbindgen emits this as `obj_bound_t` in the generated header.
 */
typedef struct {
  /**
   * Key bytes pointer. `NULL` = unbounded.
   */
  const uint8_t *ptr;
  /**
   * Length of the key in bytes. Must be `0` when `ptr` is `NULL`.
   */
  uintptr_t len;
  /**
   * `true` → `Bound::Included`; `false` → `Bound::Excluded`.
   */
  bool inclusive;
} obj_bound_t;

/**
 * One secondary-index maintenance entry: the index `index_name` is
 * to gain (or lose) the document under the field key in
 * `key[0..key_len]`.
 *
 * `key` is the ORDER-PRESERVING field encoding of the indexed
 * value, produced by
 * [`obj_index_key_encode`](crate::obj_index_key_encode). obj
 * composes the kind-specific storage key (it appends the document
 * id for `Standard` / `Each` / `Composite`, uses the key as-is with
 * the id as value for `Unique`); the caller supplies only the field
 * encoding.
 */
typedef struct {
  /**
   * NUL-terminated UTF-8 name of the index this entry maintains.
   * Must name an `Active` index on the collection or the call
   * returns `OBJ_ERR_NOT_FOUND`.
   */
  const char *index_name;
  /**
   * Pointer to the order-preserving field-key bytes. May be NULL
   * IFF `key_len == 0`.
   */
  const uint8_t *key;
  /**
   * Length of the field-key bytes at `key`.
   */
  uintptr_t key_len;
} obj_index_entry_t;

/**
 * Scalar value-kind selector for [`obj_index_key_encode`]. Maps a
 * C-side primitive onto the matching `obj_core::codec::Dynamic`
 * scalar so the produced bytes are obj's order-preserving field
 * encoding — the SAME encoding the typed Rust write path produces
 * via `extract_index_keys`.
 *
 * `int32_t` repr (like [`obj_sync_mode_t`]) for cbindgen-stable
 * layout: cbindgen emits a `typedef int32_t obj_index_value_kind_t;`
 * plus `#define`-style constants.
 */
typedef int32_t obj_index_value_kind_t;

/**
 * `SyncMode` selector for [`obj_config_t::sync_mode`].
 *
 * Three variants, mapping 1:1 to [`obj_engine::SyncMode`]. Values are
 * chosen for cbindgen-stable layout: `int32_t` repr keeps the
 * type word-aligned for the surrounding `obj_config_t`.
 */
typedef int32_t obj_sync_mode_t;

/**
 * Flat C struct mirroring [`obj_engine::Config`]'s public knobs.
 *
 * # Forward-compatibility convention
 *
 * The **first** field is `struct_size`, the byte size of the
 * `obj_config_t` the *caller* was compiled against
 * (`sizeof(obj_config_t)`). This is the standard C-ABI struct-
 * versioning trick: it lets the library grow the struct with new
 * trailing fields in future minor releases WITHOUT breaking
 * callers compiled against an older, shorter layout, and without
 * minting a fresh `obj_open_with_config2` entry point.
 *
 * Callers MUST set `struct_size = sizeof(obj_config_t)` before
 * calling [`obj_open_with_config`]. The library:
 *
 * - reads `struct_size` first and rejects a value it cannot make
 *   sense of (smaller than the v1 layout, or absurdly large) with
 *   [`OBJ_ERR_INVALID_ARG`];
 * - reads ONLY the fields the caller's declared `struct_size`
 *   covers, so an older caller's shorter struct never causes the
 *   library to read past the caller's allocation;
 * - treats `struct_size == 0` as "legacy / unspecified" and falls
 *   back to reading the full current layout — convenient for the
 *   common `obj_config_t cfg = {0}; cfg.struct_size = sizeof cfg;`
 *   idiom while still tolerating a forgotten assignment defensively.
 *
 * New fields added in future releases are appended AFTER the
 * existing fields and documented as "honoured only when
 * `struct_size` covers this field; otherwise the engine default
 * applies".
 *
 * # Field defaults
 *
 * Field-by-field defaults mirror [`obj_engine::Config::default`]:
 *
 * | Field               | Default               |
 * |---------------------|-----------------------|
 * | `struct_size`       | `sizeof(obj_config_t)`|
 * | `sync_mode`         | `OBJ_SYNC_MODE_FULL`  |
 * | `busy_timeout_ms`   | `5000`                |
 * | `skip_open_check`   | `false` (0)           |
 * | `has_encryption_key`| `false` (0)           |
 * | `encryption_key`    | all-zero (ignored)    |
 */
typedef struct {
  /**
   * `sizeof(obj_config_t)` as seen by the caller. See the struct
   * doc-comment for the forward-compatibility contract. `0` is
   * tolerated as "legacy / unspecified" and read as the full
   * current layout.
   */
  uint32_t struct_size;
  /**
   * fsync primitive used after every WAL commit.
   */
  obj_sync_mode_t sync_mode;
  /**
   * Busy-lock timeout in milliseconds. `0` is treated as the
   * engine's default (5 s).
   */
  uint64_t busy_timeout_ms;
  /**
   * Skip the open-time integrity check. Non-zero = skip.
   */
  bool skip_open_check;
  /**
   * When non-zero, [`Self::encryption_key`] holds a 32-byte master
   * key the database is opened with. When zero, the
   * key bytes are ignored and the database is opened unencrypted.
   *
   * Honoured only when `struct_size` covers this field; an older
   * (shorter) caller layout is opened unencrypted regardless of
   * the bytes that happen to follow its allocation.
   */
  bool has_encryption_key;
  /**
   * 32-byte master encryption key, consulted IFF
   * [`Self::has_encryption_key`] is non-zero. Supplying a key
   * requires a libobj built with the `encryption` feature on its
   * `obj_engine` dependency; otherwise the engine returns
   * `OBJ_ERR_UNSUPPORTED` from [`obj_open_with_config`].
   */
  uint8_t encryption_key[OBJ_ENCRYPTION_KEY_LEN];
} obj_config_t;

/**
 * Flat C struct returned by [`obj_stat`].
 */
typedef struct {
  /**
   * Format major version from page 0.
   */
  uint16_t format_major;
  /**
   * Format minor version from page 0.
   */
  uint16_t format_minor;
  /**
   * On-disk page size in bytes.
   */
  uint16_t page_size;
  /**
   * Reserved padding to keep the struct's layout deterministic
   * across cbindgen versions / compilers. Always zero.
   */
  uint16_t reserved;
  /**
   * Total number of pages.
   */
  uint64_t page_count;
  /**
   * Logical file size = `page_count * page_size`.
   */
  uint64_t file_size_bytes;
  /**
   * Number of registered collections.
   */
  uint64_t collection_count;
} obj_stat_t;

/**
 * A lock could not be acquired inside the configured timeout —
 * another transaction holds the writer mutex / cross-process
 * writer byte, or the in-process pager mutex was poisoned.
 */
#define OBJ_ERR_BUSY 4

/**
 * Content-level corruption: a page CRC mismatch, malformed
 * catalog row, schema-version-from-future, B-tree invariant
 * violated, etc.
 */
#define OBJ_ERR_CORRUPTION 3

/**
 * An integrity check completed and found violations. Distinct
 * from [`OBJ_ERR_CORRUPTION`] which is the hard fail-closed shape
 * emitted by individual operations; [`OBJ_ERR_INTEGRITY`] is the
 * soft "the report has failures" shape returned by aggregate
 * diagnostic calls.
 */
#define OBJ_ERR_INTEGRITY 6

/**
 * Caller passed an invalid argument: a null handle / out-pointer
 * where one is required, a non-UTF-8 path or collection name, a
 * length that exceeds the documented maximum, etc.
 */
#define OBJ_ERR_INVALID_ARG 1

/**
 * Underlying I/O / syscall failure: file open, read, write, fsync,
 * directory enumeration, lock acquisition syscall.
 */
#define OBJ_ERR_IO 2

/**
 * The requested record / index entry / collection was not found.
 * Iterators also return this when exhausted (see
 * `obj_iter_next` docs).
 */
#define OBJ_ERR_NOT_FOUND 5

/**
 * Highest reserved code in the obj-defined range. Future error
 * codes must stay `<= OBJ_ERR_RESERVED_MAX`; this allows
 * downstream callers to reliably distinguish obj-emitted codes
 * from any they may layer on top.
 */
#define OBJ_ERR_RESERVED_MAX 1023

/**
 * Operation is not supported in this build / for this database
 * (e.g. `obj_backup_to` on an in-memory database, an attempt to
 * mutate an attached read-only attachment, an unimplemented
 * schema migration).
 */
#define OBJ_ERR_UNSUPPORTED 7

/**
 * A C string handed across the FFI boundary was not valid UTF-8.
 * Distinct from [`OBJ_ERR_INVALID_ARG`] because UTF-8 issues are
 * frequent enough on user paths / index names to merit their own
 * signal.
 */
#define OBJ_ERR_UTF8 8

/**
 * `bool` field. The value buffer is exactly 1 byte; `0` ⇒ `false`,
 * any non-zero ⇒ `true`.
 */
#define OBJ_INDEX_VALUE_BOOL 0

/**
 * Raw bytes field. The value buffer is `value_len` arbitrary bytes
 * (embedded NULs permitted — the bytes encoding is length-prefixed).
 */
#define OBJ_INDEX_VALUE_BYTES 5

/**
 * `f64` field. The value buffer is exactly 8 bytes interpreted in
 * HOST byte order (read straight from a C `double`).
 */
#define OBJ_INDEX_VALUE_F64 3

/**
 * `i64` field. The value buffer is exactly 8 bytes interpreted in
 * HOST byte order (read straight from a C `int64_t`).
 */
#define OBJ_INDEX_VALUE_I64 2

/**
 * UTF-8 string field. The value buffer is `value_len` bytes of
 * UTF-8 (NOT NUL-terminated; the length is explicit). A buffer
 * containing an embedded NUL byte is rejected — the order-
 * preserving string encoding reserves `0x00` as its terminator.
 */
#define OBJ_INDEX_VALUE_STRING 4

/**
 * `u64` field. The value buffer is exactly 8 bytes interpreted in
 * HOST byte order (read straight from a C `uint64_t`).
 */
#define OBJ_INDEX_VALUE_U64 1

/**
 * Operation succeeded.
 */
#define OBJ_OK 0

/**
 * Strongest durability — survives system-wide power loss.
 */
#define OBJ_SYNC_MODE_FULL 0

/**
 * Process-crash / kernel-panic durability.
 */
#define OBJ_SYNC_MODE_NORMAL 1

/**
 * No durability call. Tests and benchmarks only.
 */
#define OBJ_SYNC_MODE_OFF 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Take a hot backup of `db` to `dest`. The destination MUST NOT
 * already exist.
 *
 * # Safety
 *
 * - `db` must be a live db handle.
 * - `dest` must be a NUL-terminated UTF-8 C string.
 */
 obj_error_t obj_backup_to(obj_db_t *db, const char *dest);

/**
 * Free a buffer returned by an `obj_doc_get` / iteration call.
 * Pairs with the [`alloc_bytes`] allocation. Null-tolerant;
 * passing a pointer that did NOT come from libobj is undefined
 * behaviour.
 *
 * # Safety
 *
 * - `ptr` may be NULL (no-op).
 * - If non-null, `ptr` MUST have been produced by a prior
 *   libobj call that documents this buffer-ownership convention.
 */
 void obj_buf_free(uint8_t *ptr);

/**
 * Close a database handle. Null-tolerant.
 *
 * # Safety
 *
 * - If non-null, `db` must have been returned by [`obj_open`] /
 *   [`obj_open_with_config`] and not yet freed. After this call
 *   returns the pointer is dangling — the caller must not use it
 *   again.
 */
 void obj_close(obj_db_t *db);

/**
 * Count every doc in `collection`.
 *
 * # Safety
 *
 * - `txn` must be live; `collection` NUL-terminated UTF-8;
 *   `out_count` writable.
 */
 obj_error_t obj_count_all(obj_read_txn_t *txn, const char *collection, uint64_t *out_count);

/**
 * Count index B-tree entries inside the range described by `lower` and
 * `upper`. Bound semantics match [`obj_iter_index_range`].
 *
 * # Safety
 *
 * As [`obj_iter_index_range`] plus `out_count` writable.
 */

obj_error_t obj_count_index_range(obj_read_txn_t *txn,
                                  const char *collection,
                                  const char *index_name,
                                  obj_bound_t lower,
                                  obj_bound_t upper,
                                  uint64_t *out_count);

/**
 * Delete the document at `id` in `collection` AND remove its
 * secondary-index entries given the caller-supplied `remove` field
 * keys. Returns `OBJ_ERR_NOT_FOUND` if `id` is absent.
 *
 * As with [`obj_doc_update_indexed`], obj cannot re-derive the
 * index keys from stored bytes, so the caller supplies the field
 * keys the document indexed under.
 *
 * Transaction contract: if index maintenance fails after the primary
 * delete is staged, the transaction remains uncommitted but may be
 * dirty; call [`obj_txn_rollback`] rather than committing it to
 * preserve atomicity.
 *
 * # Safety
 *
 * As [`obj_doc_insert_indexed`]; `remove` / `remove_count` follow
 * the `entries` contract.
 */

obj_error_t obj_doc_delete_indexed(obj_write_txn_t *txn,
                                   const char *collection,
                                   uint64_t id,
                                   const obj_index_entry_t *remove,
                                   uintptr_t remove_count);

/**
 * Delete the document at `id` in `collection`. Returns
 * `OBJ_ERR_NOT_FOUND` if the id is absent.
 *
 * **Secondary indexes are NOT maintained**: a delete
 * through this path leaves any secondary-index entry behind. Use
 * [`obj_doc_delete_indexed`] to remove the index entries too.
 *
 * # Safety
 *
 * As [`obj_doc_update_raw`].
 */
 obj_error_t obj_doc_delete_raw(obj_write_txn_t *txn, const char *collection, uint64_t id);

/**
 * Fetch the document at `id` in `collection`. On `OBJ_OK` the
 * caller owns `*out_payload` (length `*out_payload_len`) and
 * MUST free it via `obj_buf_free`. Returns
 * `OBJ_ERR_NOT_FOUND` if the document is absent.
 *
 * # Safety
 *
 * - `txn` must be a live read txn handle.
 * - `collection` must be a non-null NUL-terminated UTF-8 string.
 * - `out_payload` and `out_payload_len` must be writable pointers.
 */

obj_error_t obj_doc_get(obj_read_txn_t *txn,
                        const char *collection,
                        uint64_t id,
                        uint8_t **out_payload,
                        uintptr_t *out_payload_len);

/**
 * Insert a raw-bytes document into `collection` AND maintain the
 * named secondary indexes from the caller-supplied entries. On
 * success `*out_id` is set to the freshly-allocated id.
 *
 * Unlike [`obj_doc_insert_raw`] (primary record only), this is the
 * index-maintaining write: each `entries[i]` names an
 * index and supplies the order-preserving field key (build it with
 * [`obj_index_key_encode`](crate::obj_index_key_encode)) the document
 * indexes under. obj does the kind-specific storage-key composition
 * and enforces `Unique` constraints, so the written doc is
 * immediately visible to [`obj_find_unique`](crate::obj_find_unique)
 * / [`obj_iter_index_range`](crate::obj_iter_index_range).
 *
 * Transaction contract: the primary insert + every index update
 * share one WAL transaction. An unknown index name returns
 * `OBJ_ERR_NOT_FOUND`; a `Unique` collision returns
 * `OBJ_ERR_INVALID_ARG`. On either error, the transaction is still
 * uncommitted but may be dirty; call [`obj_txn_rollback`] (or avoid
 * committing the handle) so no half-written state commits.
 *
 * # Safety
 *
 * - `txn` must be a live write-txn handle.
 * - `collection` must be a non-null NUL-terminated UTF-8 string.
 * - `payload` may be NULL IFF `payload_len == 0`.
 * - `entries` may be NULL IFF `entry_count == 0`; otherwise it must
 *   point to `entry_count` readable [`obj_index_entry_t`], each with
 *   a valid `index_name` + (`key`, `key_len`) per that struct's
 *   contract.
 * - `out_id` must be a writable `uint64_t *`.
 */

obj_error_t obj_doc_insert_indexed(obj_write_txn_t *txn,
                                   const char *collection,
                                   const uint8_t *payload,
                                   uintptr_t payload_len,
                                   const obj_index_entry_t *entries,
                                   uintptr_t entry_count,
                                   uint64_t *out_id);

/**
 * Insert a raw-bytes document into `collection`. The collection
 * is lazy-created if absent. On success `*out_id` is set to the
 * freshly-allocated id.
 *
 * **Secondary indexes are NOT maintained**: this writes
 * the primary record only, so the doc is invisible to
 * `obj_find_unique` / `obj_iter_index_range` /
 * `obj_count_index_range`. Use [`obj_doc_insert_indexed`] to
 * maintain secondary indexes on insert.
 *
 * # Safety
 *
 * - `txn` must be a live write txn handle.
 * - `collection` must be a non-null NUL-terminated UTF-8 string.
 * - `payload` may be null IFF `payload_len == 0`; otherwise it
 *   must point to `payload_len` readable bytes.
 * - `out_id` must be a writable `uint64_t *`.
 */

obj_error_t obj_doc_insert_raw(obj_write_txn_t *txn,
                               const char *collection,
                               const uint8_t *payload,
                               uintptr_t payload_len,
                               uint64_t *out_id);

/**
 * Update the document at `id` in `collection` to `payload` AND move
 * its secondary-index entries from the `remove` field keys to the
 * `add` field keys.
 *
 * obj cannot re-derive the OLD index keys from the stored opaque
 * payload, so the caller supplies BOTH arrays: `remove` is what the
 * document indexed under before, `add` is what it indexes under
 * after. Returns `OBJ_ERR_NOT_FOUND` if `id` is absent.
 *
 * Transaction contract: if index maintenance fails after the primary
 * update is staged, the transaction remains uncommitted but may be
 * dirty; call [`obj_txn_rollback`] rather than committing it to
 * preserve atomicity.
 *
 * # Safety
 *
 * As [`obj_doc_insert_indexed`] plus: `remove` / `add` each follow
 * the `entries` / `entry_count` contract; `id` must come from a
 * prior insert on the same collection.
 */

obj_error_t obj_doc_update_indexed(obj_write_txn_t *txn,
                                   const char *collection,
                                   uint64_t id,
                                   const uint8_t *payload,
                                   uintptr_t payload_len,
                                   const obj_index_entry_t *remove,
                                   uintptr_t remove_count,
                                   const obj_index_entry_t *add,
                                   uintptr_t add_count);

/**
 * Update the document at `id` in `collection` with `payload`.
 * Returns `OBJ_ERR_NOT_FOUND` if the id is absent.
 *
 * **Secondary indexes are NOT maintained**: use
 * [`obj_doc_update_indexed`] to move a document's index entries on
 * update.
 *
 * # Safety
 *
 * As [`obj_doc_insert_raw`] plus: `id` must have been returned by a
 * prior `obj_doc_insert_raw` against the same collection.
 */

obj_error_t obj_doc_update_raw(obj_write_txn_t *txn,
                               const char *collection,
                               uint64_t id,
                               const uint8_t *payload,
                               uintptr_t payload_len);

/**
 * Insert-or-replace the document at `id` in `collection` with
 * `payload`. The collection is lazy-created if absent.
 *
 * **Secondary indexes are NOT maintained**. There is no
 * `_indexed` upsert variant: an upsert that must maintain indexes
 * has to supply the OLD field keys to remove, which the
 * [`obj_doc_update_indexed`] (when the id exists) /
 * [`obj_doc_insert_indexed`] (when it does not) pair expresses
 * directly.
 *
 * # Safety
 *
 * As [`obj_doc_insert_raw`].
 */

obj_error_t obj_doc_upsert_raw(obj_write_txn_t *txn,
                               const char *collection,
                               uint64_t id,
                               const uint8_t *payload,
                               uintptr_t payload_len);

/**
 * Return the most recent error message recorded against `db`, as a
 * NUL-terminated C string. Mirrors `sqlite3_errmsg`: where
 * [`obj_strerror`](crate::obj_strerror) maps a code to a generic
 * label, this returns the SPECIFIC reason the last failing call on
 * `db` produced (e.g. `"index 'email_idx' not found"`).
 *
 * Never returns NULL:
 * - a NULL `db` yields a static `"(null db handle)"`;
 * - a handle with no recorded error yields a static `"(no error)"`.
 *
 * The returned pointer is owned by `db`; the caller MUST NOT free
 * it. `db` retains its most recent error strings in a small
 * fixed-size ring (the last 16), so a returned pointer stays valid
 * until 16 *further* error-recording calls on `db` — or on any
 * txn / iter derived from it, including from other threads — have
 * recycled its ring slot, or until [`obj_close`] frees the handle.
 * In other words there is a bounded grace window, not single-call
 * invalidation: a pointer you just obtained is NOT freed out from
 * under you by one concurrent failing call. Memory stays bounded —
 * only the most recent 16 strings are kept, however many errors the
 * handle records over its lifetime.
 *
 * Still, treat the result like `sqlite3_errmsg`: copy the string
 * promptly (before driving many more failing calls on the handle)
 * rather than holding the raw pointer indefinitely.
 *
 * # Safety
 *
 * If non-null, `db` must be a live handle returned by
 * [`obj_open`] / [`obj_open_with_config`] and not yet closed.
 */
 const char *obj_errmsg(obj_db_t *db);

/**
 * Look up a single doc by index key on a `Unique` index. The
 * caller pre-encodes `key_bytes` per the order-preserving
 * scheme. Returns `OBJ_ERR_NOT_FOUND` when no doc matches.
 *
 * # Safety
 *
 * - `txn` must be live.
 * - `collection`, `index_name`, `key` follow the usual pointer
 *   rules; `key` may be NULL when `key_len == 0`.
 * - `out_id`, `out_payload`, `out_payload_len` must be writable.
 */

obj_error_t obj_find_unique(obj_read_txn_t *txn,
                            const char *collection,
                            const char *index_name,
                            const uint8_t *key,
                            uintptr_t key_len,
                            uint64_t *out_id,
                            uint8_t **out_payload,
                            uintptr_t *out_payload_len);

/**
 * Encode a single index field `value` into obj's order-preserving
 * field-key bytes, writing the result into the caller's `out`
 * buffer.
 *
 * This is the encoder a C consumer uses to build the `key` bytes
 * of an [`crate::obj_index_entry_t`] handed to
 * [`obj_doc_insert_indexed`](crate::obj_doc_insert_indexed) /
 * `_update_indexed` / `_delete_indexed`. The bytes it produces are
 * byte-identical to what the typed Rust write path stores, so the
 * `obj_find_unique` / `obj_iter_index_range` readers find the doc.
 *
 * # Buffer contract (size query)
 *
 * On success the encoded length is written to `*out_len` and the
 * bytes to `out[0..*out_len]`, and the call returns [`OBJ_OK`].
 *
 * If `out_cap` is too small (including `out` being NULL with
 * `out_cap == 0`), the call writes the REQUIRED length to `*out_len`
 * and returns [`OBJ_ERR_INVALID_ARG`] WITHOUT touching `out`. So the
 * standard two-call idiom works: call once with `out_cap = 0` to
 * learn the size, allocate, then call again. (An encoded field is at
 * most `value_len + 5` bytes, so `value_len + 5` is always a safe
 * up-front capacity.)
 *
 * # Safety
 *
 * - `value` may be NULL IFF `value_len == 0`; otherwise it must
 *   point to `value_len` readable bytes.
 * - For fixed-width kinds (`BOOL` ⇒ 1 byte, `U64`/`I64`/`F64` ⇒
 *   8 bytes) `value_len` MUST equal the exact width or the call
 *   returns [`OBJ_ERR_INVALID_ARG`].
 * - `out` may be NULL only when `out_cap == 0` (size-query form);
 *   otherwise it must point to `out_cap` writable bytes.
 * - `out_len` must be a writable `size_t *`.
 */

obj_error_t obj_index_key_encode(obj_index_value_kind_t kind,
                                 const uint8_t *value,
                                 uintptr_t value_len,
                                 uint8_t *out,
                                 uintptr_t out_cap,
                                 uintptr_t *out_len);

/**
 * Run the full bidirectional integrity walk against `db`. Returns
 * the report through `*out_report`. On `OBJ_OK` the report holds
 * the walk's outcome (the caller checks `is_ok` via
 * [`obj_integrity_report_is_ok`]); on `OBJ_ERR_INTEGRITY` the
 * walk completed but found at least one failure. Any I/O / engine
 * error during the walk surfaces as a different error code with
 * `*out_report` set to NULL.
 *
 * # Safety
 *
 * - `db` must be a live db handle.
 * - `out_report` must be a writable `obj_integrity_report_t *`.
 */
 obj_error_t obj_integrity_check(obj_db_t *db, obj_integrity_report_t **out_report);

/**
 * Copy the Debug-formatted text of failure `index` into a fresh
 * libobj-owned buffer. Caller pairs with `obj_buf_free`.
 * Returns `OBJ_ERR_NOT_FOUND` for an out-of-range index.
 *
 * # Safety
 *
 * As [`obj_integrity_report_is_ok`] plus `out_string` /
 * `out_string_len` writable.
 */

obj_error_t obj_integrity_report_failure_at(const obj_integrity_report_t *report,
                                            uintptr_t index,
                                            uint8_t **out_string,
                                            uintptr_t *out_string_len);

/**
 * Number of failure entries in the report.
 *
 * # Safety
 *
 * As [`obj_integrity_report_is_ok`].
 */
 uintptr_t obj_integrity_report_failure_count(const obj_integrity_report_t *report);

/**
 * Free an integrity report. Null-tolerant.
 *
 * # Safety
 *
 * If non-null, `report` must be a handle from
 * [`obj_integrity_check`] not yet freed.
 */
 void obj_integrity_report_free(obj_integrity_report_t *report);

/**
 * `true` iff the report carries no failures. Null-tolerant —
 * returns `false` for a NULL report (a NULL report is by
 * definition not a clean one).
 *
 * # Safety
 *
 * If non-null, `report` must be a handle from
 * [`obj_integrity_check`] not yet freed.
 */
 bool obj_integrity_report_is_ok(const obj_integrity_report_t *report);

/**
 * Number of pages the walker visited.
 *
 * # Safety
 *
 * If non-null, `report` must be a handle from
 * [`obj_integrity_check`] not yet freed.
 */
 uint64_t obj_integrity_report_pages_checked(const obj_integrity_report_t *report);

/**
 * Construct an iterator over every doc in `collection`, snapshot-
 * consistent against `txn`. Caller pairs with [`obj_iter_next`]
 * and [`obj_iter_free`].
 *
 * # Safety
 *
 * - `txn` must be a live read-txn handle.
 * - `collection` must be a NUL-terminated UTF-8 C string.
 * - `out_iter` must be a writable `obj_iter_t *`.
 */
 obj_error_t obj_iter_all(obj_read_txn_t *txn, const char *collection, obj_iter_t **out_iter);

/**
 * Free an iterator handle. Null-tolerant.
 *
 * # Safety
 *
 * If non-null, `iter` must be a handle returned by
 * [`obj_iter_all`] / [`obj_iter_index_range`].
 */
 void obj_iter_free(obj_iter_t *iter);

/**
 * Construct an iterator over the index range described by `lower` and
 * `upper` on `index_name` in `collection`. A bound with `ptr == NULL`
 * and `len == 0` means unbounded on that side; `inclusive` selects
 * `Included` vs `Excluded`.
 *
 * # Safety
 *
 * - `txn`, `collection`, `index_name`, `out_iter` must follow the
 *   usual non-null + NUL-terminated conventions.
 * - `lower.ptr` / `upper.ptr` may be NULL (paired with `len = 0`)
 *   or point to `len` readable bytes.
 */

obj_error_t obj_iter_index_range(obj_read_txn_t *txn,
                                 const char *collection,
                                 const char *index_name,
                                 obj_bound_t lower,
                                 obj_bound_t upper,
                                 obj_iter_t **out_iter);

/**
 * Step the iterator. On `OBJ_OK` the caller owns `*out_payload`
 * (length `*out_payload_len`) and MUST free it with
 * `obj_buf_free`. Returns `OBJ_ERR_NOT_FOUND` at end-of-
 * iteration; a real engine failure surfaces as the corresponding
 * error code.
 *
 * # Safety
 *
 * - `iter` must be a live iterator handle.
 * - `out_id`, `out_payload`, `out_payload_len` must be writable.
 */

obj_error_t obj_iter_next(obj_iter_t *iter,
                          uint64_t *out_id,
                          uint8_t **out_payload,
                          uintptr_t *out_payload_len);

/**
 * Open or create a file-backed database at `path`. Default
 * configuration ([`obj_engine::Config::default`]).
 *
 * On success: `*out_db` is set to a newly-allocated [`obj_db_t`]
 * (caller must free via [`obj_close`]) and `OBJ_OK` is returned.
 * On failure: `*out_db` is set to NULL and an error code is
 * returned.
 *
 * # Safety
 *
 * - `path` must be a non-null pointer to a NUL-terminated UTF-8
 *   string. The pointee is read but not retained.
 * - `out_db` must be a non-null pointer to a writable
 *   `obj_db_t*`. The pointee is unconditionally written before
 *   return (NULL on failure).
 */
 obj_error_t obj_open(const char *path, obj_db_t **out_db);

/**
 * As [`obj_open`] but with caller-supplied configuration.
 *
 * `config->struct_size` MUST be set to `sizeof(obj_config_t)` (or
 * left `0` for the legacy / full-layout reading). See the
 * [`obj_config_t`] doc-comment for the forward-compatibility
 * contract. An explicit `struct_size` that is smaller than the
 * oldest understood layout, or larger than this library's current
 * layout, is rejected with [`OBJ_ERR_INVALID_ARG`].
 *
 * # Safety
 *
 * - `path` must be a non-null pointer to a NUL-terminated UTF-8
 *   string.
 * - `config` must be a non-null pointer to an [`obj_config_t`]
 *   whose first `config->struct_size` bytes (or, when
 *   `struct_size == 0`, whose full current-layout size) are
 *   readable and initialised. The pointee is read but not
 *   retained.
 * - `out_db` must be a non-null pointer to a writable
 *   `obj_db_t*`.
 */
 obj_error_t obj_open_with_config(const char *path, const obj_config_t *config, obj_db_t **out_db);

/**
 * Populate `out_stat` with a snapshot of the db's header +
 * collection-count summary.
 *
 * # Safety
 *
 * - `db` must be live.
 * - `out_stat` must be a writable `obj_stat_t *`.
 */
 obj_error_t obj_stat(obj_db_t *db, obj_stat_t *out_stat);

/**
 * Return a static C string describing `code`. Never returns NULL.
 *
 * # Safety
 *
 * The returned pointer points into the read-only data segment of
 * the loaded library; it has `'static` lifetime and MUST NOT be
 * freed. It is safe to read until the dynamic library is
 * unloaded.
 */
 const char *obj_strerror(obj_error_t code);

/**
 * Begin a read transaction against `db`. Pins a snapshot at the
 * current writer LSN.
 *
 * # Safety
 *
 * - `db` must be a valid handle returned by `obj_open*`.
 * - `out_txn` must be a writable `obj_read_txn_t *`.
 */
 obj_error_t obj_txn_begin_read(obj_db_t *db, obj_read_txn_t **out_txn);

/**
 * Begin a write transaction against `db`. Acquires the writer
 * slot (subject to the configured busy timeout).
 *
 * # Safety
 *
 * - `db` must be a valid handle returned by `obj_open*` and not
 *   yet closed.
 * - `out_txn` must be a writable `obj_write_txn_t *`. On success
 *   it is set to a fresh handle; on failure it is set to NULL.
 */
 obj_error_t obj_txn_begin_write(obj_db_t *db, obj_write_txn_t **out_txn);

/**
 * Commit a write transaction. Consumes the handle — the C
 * caller MUST NOT touch `txn` again after this returns.
 *
 * # Safety
 *
 * `txn` must be a non-null handle returned by
 * [`obj_txn_begin_write`] and not yet committed / rolled back.
 */
 obj_error_t obj_txn_commit(obj_write_txn_t *txn);

/**
 * End a read transaction. Releases the reader slot + the
 * pinned-snapshot WAL anchor. Null-tolerant.
 *
 * # Safety
 *
 * If non-null, `txn` must be a handle returned by
 * [`obj_txn_begin_read`] and not yet ended.
 */
 void obj_txn_end_read(obj_read_txn_t *txn);

/**
 * Roll back a write transaction. Null-tolerant.
 *
 * # Safety
 *
 * If non-null, `txn` must be a handle returned by
 * [`obj_txn_begin_write`] and not yet committed / rolled back.
 */
 void obj_txn_rollback(obj_write_txn_t *txn);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIBOBJ_H */


